// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDY9tO-Y77Nxo2bpeWTwnHGWfLvJ14A98',
    appId: '1:219894648569:web:5a4dd812700f30056f5c28',
    messagingSenderId: '219894648569',
    projectId: 'banco-79e5a',
    authDomain: 'banco-79e5a.firebaseapp.com',
    storageBucket: 'banco-79e5a.firebasestorage.app',
    measurementId: 'G-ZZCLZGGDK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJIkQhAqjz1fWJcGGAU9s2Rv8MfQUMgdw',
    appId: '1:219894648569:android:66d26cc3234935a16f5c28',
    messagingSenderId: '219894648569',
    projectId: 'banco-79e5a',
    storageBucket: 'banco-79e5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-HE8qdcyh-ZVNktlIPcRX6ytI3L2QE3c',
    appId: '1:219894648569:ios:783b38ed91f1be056f5c28',
    messagingSenderId: '219894648569',
    projectId: 'banco-79e5a',
    storageBucket: 'banco-79e5a.firebasestorage.app',
    iosBundleId: 'com.example.bancod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-HE8qdcyh-ZVNktlIPcRX6ytI3L2QE3c',
    appId: '1:219894648569:ios:783b38ed91f1be056f5c28',
    messagingSenderId: '219894648569',
    projectId: 'banco-79e5a',
    storageBucket: 'banco-79e5a.firebasestorage.app',
    iosBundleId: 'com.example.bancod',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDY9tO-Y77Nxo2bpeWTwnHGWfLvJ14A98',
    appId: '1:219894648569:web:44dd14d6838724796f5c28',
    messagingSenderId: '219894648569',
    projectId: 'banco-79e5a',
    authDomain: 'banco-79e5a.firebaseapp.com',
    storageBucket: 'banco-79e5a.firebasestorage.app',
    measurementId: 'G-916YN9BQ71',
  );
}
